### ISSUE TITLE
php 7.2 windows

### ISSUE THREAD

**Issue by vova-melnykovych** [m6w6/ext-apfd#2]
Is this possible to update this extension for Windows?  Here is *.dll file only for 5.6 https://pecl.php.net/package/apfd/1.0.1/windows

**Comment by m6w6** [comment]
We'd probably need help from @Jan-E or @weltling

**Comment by Jan-E** [comment]
Try the php_apfd.dll's in my PHP 7 builds:
https://www.apachelounge.com/viewtopic.php?t=6359

**Comment by vova-melnykovych** [comment]
Thank you. Everything works great

**Comment by Jan-E** [comment]
Nevertheless: can @weltling run the script to generate the PHP 7.x dll's on PECL for the 1.0.1 release?
