### ISSUE TITLE
Problems when sending a PATCH request without a webserver

### ISSUE THREAD

**Issue by major-mayer** [m6w6/ext-apfd#3]
Hello,
I really like this extension, because it allows me to send PATCH/ PUT/ ... requests with a form-data body.
I'm using the Slim Framework to handle all requests.
It works great when I send a normal request with eg.  Postman, where the $_POST variable gets populated correctly.

However for my unit tests i'm using PHPUnit and have to create the reqests manually with this method:
`$req = Request::createFromEnvironment($env)->withParsedBody($body)`
It is also described here: http://www.slimframework.com/docs/v3/cookbook/environment.html

The creation works good and the the body seems to include all the form-data parameters, but when i later try to get the parameters from the $_POST variable, it is empty.
Honestly I'm not sure if it's a problem with the requests creation or the parsing of the requests later when its submitted.
Maybe you can look at it and find the reason why it does not work.  Thanks

**Comment by m6w6** [comment]
Hi, I'm pretty sure any mock or the slim framework won't alter the global environment like PHP's superglobals.
